import { IFishItem } from 'kan/types';

export const fishData: IFishItem[] = [
  {
    id: 'fish_001',
    name: 'Clownfish',
    image: '/fish/fish-1.png',
    speed: 3,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      seashells: 5,
      tokens: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_002',
    name: 'Blue Tang',
    image: '/fish/fish-2.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 5,
      seashells: 10,
      tokens: 20,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_003',
    name: 'Whale Shark',
    image: '/fish/fish-3.png',
    speed: 1,
    size: 'large',
    rarity: 'legendary',
    hp: 15,
    requiredAttacks: 15,
    rewards: {
      fish: 50,
      seashells: 0,
      tokens: 100,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_004',
    name: 'Lionfish',
    image: '/fish/fish-4.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      seashells: 3,
      tokens: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_005',
    name: 'Mahi Mahi',
    image: '/fish/fish-5.png',
    speed: 4,
    size: 'large',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 30,
      seashells: 5,
      tokens: 10,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_006',
    name: 'Anglerfish',
    image: '/fish/fish-6.png',
    speed: 1,
    size: 'medium',
    rarity: 'epic',
    hp: 8,
    requiredAttacks: 8,
    rewards: {
      fish: 20,
      seashells: 15,
      tokens: 30,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'fish_007',
    name: 'Tuna',
    image: '/fish/fish-7.png',
    speed: 3,
    size: 'large',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 25,
      seashells: 8,
      tokens: 5,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_008',
    name: 'Swordfish',
    image: '/fish/fish-8.png',
    speed: 5,
    size: 'medium',
    rarity: 'epic',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      seashells: 10,
      tokens: 40,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_009',
    name: 'Jellyfish',
    image: '/fish/fish-9.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 5,
      seashells: 2,
      tokens: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_010',
    name: 'Shark',
    image: '/fish/fish-10.png',
    speed: 2,
    size: 'large',
    rarity: 'legendary',
    hp: 15,
    requiredAttacks: 15,
    rewards: {
      fish: 100,
      seashells: 5,
      tokens: 150,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_011',
    name: 'Barracuda',
    image: '/fish/fish-11.png',
    speed: 5,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 15,
      seashells: 7,
      tokens: 15,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_012',
    name: 'Moray Eel',
    image: '/fish/fish-12.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 8,
      seashells: 4,
      tokens: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_013',
    name: 'Manta Ray',
    image: '/fish/fish-13.png',
    speed: 1,
    size: 'large',
    rarity: 'epic',
    hp: 10,
    requiredAttacks: 10,
    rewards: {
      fish: 40,
      seashells: 20,
      tokens: 50,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_014',
    name: 'Angelfish',
    image: '/fish/fish-14.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 18,
      seashells: 10,
      tokens: 25,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_015',
    name: 'Piranha',
    image: '/fish/fish-15.png',
    speed: 6,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      seashells: 2,
      tokens: 0,
    },
    habitat: 'river',
  },
  {
    id: 'fish_016',
    name: 'Sea Turtle',
    image: '/fish/fish-16.png',
    speed: 2,
    size: 'large',
    rarity: 'epic',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      seashells: 15,
      tokens: 45,
    },
    habitat: 'reef',
  },
];
