import { IFishItem } from 'kan/types';

export const fishData: IFishItem[] = [
  {
    id: 'fish_001',
    name: 'Clownfish',
    image: '/fish/fish-1.png',
    speed: 3,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      shells: 5,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_002',
    name: 'Blue Tang',
    image: '/fish/fish-2.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 5,
      shells: 10,
      coins: 20,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_003',
    name: 'Whale Shark',
    image: '/fish/fish-3.png',
    speed: 1,
    size: 'large',
    rarity: 'legendary',
    hp: 15,
    requiredAttacks: 15,
    rewards: {
      fish: 50,
      shells: 0,
      coins: 100,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_004',
    name: 'Lionfish',
    image: '/fish/fish-4.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 3,
      coins: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_005',
    name: 'Mahi Mahi',
    image: '/fish/fish-5.png',
    speed: 4,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 30,
      shells: 5,
      coins: 10,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_006',
    name: 'Rainbowfish',
    image: '/fish/fish-6.png',
    speed: 1,
    size: 'medium',
    rarity: 'epic',
    hp: 8,
    requiredAttacks: 8,
    rewards: {
      fish: 20,
      shells: 15,
      coins: 30,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'fish_007',
    name: 'Tuna',
    image: '/fish/fish-7.png',
    speed: 3,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 25,
      shells: 8,
      coins: 5,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_008',
    name: 'Swordfish',
    image: '/fish/fish-8.png',
    speed: 5,
    size: 'medium',
    rarity: 'epic',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      shells: 10,
      coins: 40,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_009',
    name: 'Blue-green Chromis',
    image: '/fish/fish-9.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 5,
      shells: 2,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_010',
    name: 'Shark',
    image: '/fish/fish-10.png',
    speed: 2,
    size: 'large',
    rarity: 'legendary',
    hp: 15,
    requiredAttacks: 15,
    rewards: {
      fish: 100,
      shells: 5,
      coins: 150,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_011',
    name: 'Barracuda',
    image: '/fish/fish-11.png',
    speed: 5,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 15,
      shells: 7,
      coins: 15,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_012',
    name: 'Redtail Catfish',
    image: '/fish/fish-12.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 8,
      shells: 4,
      coins: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_013',
    name: 'Water Filtration',
    image: '/fish/fish-13.png',
    speed: 1,
    size: 'medium',
    rarity: 'epic',
    hp: 10,
    requiredAttacks: 10,
    rewards: {
      fish: 40,
      shells: 20,
      coins: 50,
    },
    habitat: 'open ocean',
  },
  {
    id: 'fish_014',
    name: 'Angelfish',
    image: '/fish/fish-14.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 18,
      shells: 10,
      coins: 25,
    },
    habitat: 'reef',
  },
  {
    id: 'fish_015',
    name: 'Piranha',
    image: '/fish/fish-15.png',
    speed: 6,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      shells: 2,
      coins: 0,
    },
    habitat: 'river',
  },
  {
    id: 'fish_016',
    name: 'Zebra Shark',
    image: '/fish/fish-16.png',
    speed: 2,
    size: 'large',
    rarity: 'epic',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 15,
      coins: 45,
    },
    habitat: 'reef',
  },
];
