import { IFishItem } from 'kan/types';

export const shallowReefFish: IFishItem[] = [
  {
    id: 'shallow_001',
    name: 'Piranha',
    image: '/fish/shallow/shallow-1.png',
    speed: 6,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      shells: 2,
      coins: 0,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_002',
    name: 'Zebra Shark',
    image: '/fish/shallow/shallow-2.png',
    speed: 2,
    size: 'large',
    rarity: 'epic',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 15,
      coins: 45,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_003',
    name: 'Royal Gramma',
    image: '/fish/shallow/shallow-3.png',
    speed: 2,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 12,
      shells: 3,
      coins: 5,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_004',
    name: 'Mandarinfish',
    image: '/fish/shallow/shallow-4.png',
    speed: 1,
    size: 'small',
    rarity: 'epic',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 15,
      shells: 8,
      coins: 12,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_005',
    name: 'Gobies',
    image: '/fish/shallow/shallow-5.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 7,
      shells: 3,
      coins: 0,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_006',
    name: 'Yellow Tang',
    image: '/fish/shallow/shallow-6.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 14,
      shells: 4,
      coins: 8,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_007',
    name: 'Harlequin Filefish',
    image: '/fish/shallow/shallow-7.png',
    speed: 1,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 10,
      shells: 6,
      coins: 15,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_008',
    name: 'Cleaner Wrasse',
    image: '/fish/shallow/shallow-8.png',
    speed: 4,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 5,
      shells: 2,
      coins: 0,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_009',
    name: 'Bannerfish',
    image: '/fish/shallow/shallow-9.png',
    speed: 3,
    size: 'medium',
    rarity: 'rare',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 18,
      shells: 7,
      coins: 12,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_010',
    name: 'Pajama Cardinalfish',
    image: '/fish/shallow/shallow-10.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 9,
      shells: 3,
      coins: 5,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_011',
    name: 'Saddleback Clownfish',
    image: '/fish/shallow/shallow-11.png',
    speed: 3,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 5,
      coins: 10,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_012',
    name: 'Pipefish',
    image: '/fish/shallow/shallow-12.png',
    speed: 1,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 10,
      shells: 4,
      coins: 8,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_013',
    name: 'Orange Fairy Wrasse',
    image: '/fish/shallow/shallow-13.png',
    speed: 3,
    size: 'small',
    rarity: 'epic',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 20,
      shells: 8,
      coins: 15,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_014',
    name: 'Red Firefish',
    image: '/fish/shallow/shallow-14.png',
    speed: 2,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 12,
      shells: 4,
      coins: 10,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_015',
    name: 'Bicolor Blenny',
    image: '/fish/shallow/shallow-15.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 8,
      shells: 3,
      coins: 0,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_016',
    name: 'Moorish Idol',
    image: '/fish/shallow/shallow-16.png',
    speed: 4,
    size: 'medium',
    rarity: 'epic',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 25,
      shells: 10,
      coins: 20,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_017',
    name: 'Sixline Wrasse',
    image: '/fish/shallow/shallow-17.png',
    speed: 2,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 14,
      shells: 6,
      coins: 12,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_018',
    name: 'Peacock Mantis Shrimp',
    image: '/fish/shallow/shallow-18.png',
    speed: 3,
    size: 'small',
    rarity: 'epic',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 18,
      shells: 12,
      coins: 15,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_019',
    name: 'Convict Tang',
    image: '/fish/shallow/shallow-19.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 13,
      shells: 5,
      coins: 8,
    },
    habitat: 'shallow reef',
  },
  {
    id: 'shallow_020',
    name: 'Blackcap Basslet',
    image: '/fish/shallow/shallow-20.png',
    speed: 2,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 7,
      coins: 10,
    },
    habitat: 'shallow reef',
  },
];

export const reefFish: IFishItem[] = [
  // Reef Habitat Fish
  {
    id: 'reef_001',
    name: 'Clownfish',
    image: '/fish/reef/reef-1.png',
    speed: 3,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 10,
      shells: 5,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_002',
    name: 'Blue Tang',
    image: '/fish/reef/reef-2.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 5,
      shells: 10,
      coins: 20,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_003',
    name: 'Lionfish',
    image: '/fish/reef/reef-4.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 3,
      coins: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_004',
    name: 'Blue-green Chromis',
    image: '/fish/reef/reef-4.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 5,
      shells: 2,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_005',
    name: 'Barracuda',
    image: '/fish/reef/reef-5.png',
    speed: 5,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 15,
      shells: 7,
      coins: 15,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_006',
    name: 'Redtail Catfish',
    image: '/fish/reef/reef-6.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 8,
      shells: 4,
      coins: 1,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_007',
    name: 'Angelfish',
    image: '/fish/reef/reef-7.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 18,
      shells: 10,
      coins: 25,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_008',
    name: 'Parrotfish',
    image: '/fish/reef/reef-8.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 12,
      shells: 8,
      coins: 2,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_009',
    name: 'Butterflyfish',
    image: '/fish/reef/reef-9.png',
    speed: 3,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 10,
      shells: 5,
      coins: 10,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_010',
    name: 'Moorish Idol',
    image: '/fish/reef/reef-10.png',
    speed: 4,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 8,
      coins: 5,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_011',
    name: 'Gobies',
    image: '/fish/reef/reef-11.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 8,
      shells: 4,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_012',
    name: 'Firefish',
    image: '/fish/reef/reef-12.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 6,
      shells: 3,
      coins: 2,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_013',
    name: 'Mandarinfish',
    image: '/fish/reef/reef-13.png',
    speed: 1,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 10,
      shells: 5,
      coins: 10,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_014',
    name: 'Wrasse',
    image: '/fish/reef/reef-14.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 12,
      shells: 6,
      coins: 5,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_015',
    name: 'Bicolor Blenny',
    image: '/fish/reef/reef-15.png',
    speed: 1,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 8,
      shells: 4,
      coins: 5,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_016',
    name: 'Cleaner Shrimp',
    image: '/fish/reef/reef-16.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 1,
    requiredAttacks: 1,
    rewards: {
      fish: 5,
      shells: 3,
      coins: 0,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_017',
    name: 'Royal Gramma',
    image: '/fish/reef/reef-17.png',
    speed: 2,
    size: 'small',
    rarity: 'epic',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 15,
      shells: 7,
      coins: 20,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_018',
    name: 'Anthias',
    image: '/fish/reef/reef-18.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 7,
      shells: 4,
      coins: 2,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_019',
    name: 'Flame Angel',
    image: '/fish/reef/reef-19.png',
    speed: 3,
    size: 'small',
    rarity: 'rare',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 15,
      shells: 5,
      coins: 10,
    },
    habitat: 'reef',
  },
  {
    id: 'reef_020',
    name: 'Sailfin Tang',
    image: '/fish/reef/reef-20.png',
    speed: 2,
    size: 'medium',
    rarity: 'common',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 10,
      shells: 5,
      coins: 8,
    },
    habitat: 'reef',
  },
];

export const openOceanFish: IFishItem[] = [
  {
    id: 'open_ocean_001',
    name: 'Blue Marlin',
    image: '/fish/open/open-1.png',
    speed: 5,
    size: 'large',
    rarity: 'epic',
    hp: 12,
    requiredAttacks: 12,
    rewards: {
      fish: 60,
      shells: 25,
      coins: 75,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_002',
    name: 'Mako Shark',
    image: '/fish/open/open-2.png',
    speed: 5,
    size: 'large',
    rarity: 'rare',
    hp: 10,
    requiredAttacks: 10,
    rewards: {
      fish: 55,
      shells: 20,
      coins: 65,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_003',
    name: 'Swordfish',
    image: '/fish/open/open-3.png',
    speed: 6,
    size: 'medium',
    rarity: 'epic',
    hp: 8,
    requiredAttacks: 8,
    rewards: {
      fish: 50,
      shells: 20,
      coins: 70,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_004',
    name: 'Albacore Tuna',
    image: '/fish/open/open-4.png',
    speed: 4,
    size: 'large',
    rarity: 'rare',
    hp: 9,
    requiredAttacks: 9,
    rewards: {
      fish: 45,
      shells: 18,
      coins: 60,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_005',
    name: 'Pelagic Stingray',
    image: '/fish/open/open-5.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 12,
      coins: 40,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_006',
    name: 'Sunfish',
    image: '/fish/open/open-6.png',
    speed: 2,
    size: 'large',
    rarity: 'rare',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      shells: 14,
      coins: 50,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_007',
    name: 'Mahi-Mahi',
    image: '/fish/open/open-7.png',
    speed: 5,
    size: 'medium',
    rarity: 'epic',
    hp: 9,
    requiredAttacks: 9,
    rewards: {
      fish: 50,
      shells: 20,
      coins: 65,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_008',
    name: 'Humpback Whale',
    image: '/fish/open/open-8.png',
    speed: 1,
    size: 'large',
    rarity: 'epic',
    hp: 15,
    requiredAttacks: 15,
    rewards: {
      fish: 75,
      shells: 30,
      coins: 100,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_009',
    name: 'Sailfish',
    image: '/fish/open/open-9.png',
    speed: 7,
    size: 'large',
    rarity: 'rare',
    hp: 10,
    requiredAttacks: 10,
    rewards: {
      fish: 55,
      shells: 22,
      coins: 65,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_010',
    name: 'Cobia',
    image: '/fish/open/open-10.png',
    speed: 4,
    size: 'medium',
    rarity: 'common',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 25,
      shells: 10,
      coins: 30,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_011',
    name: 'Orca',
    image: '/fish/open/open-11.png',
    speed: 4,
    size: 'large',
    rarity: 'epic',
    hp: 12,
    requiredAttacks: 12,
    rewards: {
      fish: 60,
      shells: 25,
      coins: 80,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_012',
    name: 'Tuna',
    image: '/fish/open/open-12.png',
    speed: 4,
    size: 'medium',
    rarity: 'rare',
    hp: 8,
    requiredAttacks: 8,
    rewards: {
      fish: 40,
      shells: 16,
      coins: 50,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_013',
    name: 'Thresher Shark',
    image: '/fish/open/open-13.png',
    speed: 5,
    size: 'medium',
    rarity: 'rare',
    hp: 9,
    requiredAttacks: 9,
    rewards: {
      fish: 45,
      shells: 18,
      coins: 55,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_014',
    name: 'Great White Shark',
    image: '/fish/open/open-14.png',
    speed: 6,
    size: 'large',
    rarity: 'epic',
    hp: 14,
    requiredAttacks: 14,
    rewards: {
      fish: 70,
      shells: 28,
      coins: 90,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_015',
    name: 'Bottlenose Dolphin',
    image: '/fish/open/open-15.png',
    speed: 5,
    size: 'medium',
    rarity: 'common',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      shells: 14,
      coins: 45,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_016',
    name: 'Spotted Eagle Ray',
    image: '/fish/open/open-16.png',
    speed: 3,
    size: 'large',
    rarity: 'rare',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 12,
      coins: 40,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_017',
    name: 'Lionfish',
    image: '/fish/open/open-17.png',
    speed: 3,
    size: 'small',
    rarity: 'common',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 20,
      shells: 8,
      coins: 25,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_018',
    name: 'Barracuda',
    image: '/fish/open/open-18.png',
    speed: 6,
    size: 'medium',
    rarity: 'epic',
    hp: 9,
    requiredAttacks: 9,
    rewards: {
      fish: 50,
      shells: 20,
      coins: 70,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_019',
    name: 'Wahoo',
    image: '/fish/open/open-19.png',
    speed: 5,
    size: 'medium',
    rarity: 'rare',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      shells: 14,
      coins: 45,
    },
    habitat: 'open ocean',
  },
  {
    id: 'open_ocean_020',
    name: 'Whale Shark',
    image: '/fish/open/open-20.png',
    speed: 2,
    size: 'large',
    rarity: 'epic',
    hp: 20,
    requiredAttacks: 20,
    rewards: {
      fish: 100,
      shells: 40,
      coins: 120,
    },
    habitat: 'open ocean',
  },
];

export const deepOceanFish: IFishItem[] = [
  {
    id: 'deep_ocean_001',
    name: 'Anglerfish',
    image: '/fish/deep/deep-1.png',
    speed: 2,
    size: 'medium',
    rarity: 'epic',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 12,
      coins: 40,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_002',
    name: 'Giant Squid',
    image: '/fish/deep/deep-2.png',
    speed: 3,
    size: 'large',
    rarity: 'rare',
    hp: 7,
    requiredAttacks: 7,
    rewards: {
      fish: 35,
      shells: 15,
      coins: 50,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_003',
    name: 'Giant Manta Ray',
    image: '/fish/deep/deep-3.png',
    speed: 4,
    size: 'large',
    rarity: 'epic',
    hp: 8,
    requiredAttacks: 8,
    rewards: {
      fish: 40,
      shells: 18,
      coins: 60,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_004',
    name: 'Goblin Shark',
    image: '/fish/deep/deep-4.png',
    speed: 3,
    size: 'medium',
    rarity: 'rare',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 25,
      shells: 10,
      coins: 30,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_005',
    name: 'Deep Sea Anglerfish',
    image: '/fish/deep/deep-5.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 12,
      shells: 4,
      coins: 10,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_006',
    name: 'Vampire Squid',
    image: '/fish/deep/deep-6.png',
    speed: 3,
    size: 'medium',
    rarity: 'rare',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 28,
      shells: 10,
      coins: 35,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_007',
    name: 'Black Swallower',
    image: '/fish/deep/deep-7.png',
    speed: 1,
    size: 'small',
    rarity: 'epic',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 20,
      shells: 8,
      coins: 25,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_008',
    name: 'Deep Sea Jellyfish',
    image: '/fish/deep/deep-8.png',
    speed: 1,
    size: 'small',
    rarity: 'common',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 15,
      shells: 6,
      coins: 15,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_009',
    name: 'Cusk Eel',
    image: '/fish/deep/deep-9.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 20,
      shells: 8,
      coins: 18,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_010',
    name: 'Pelagic Thresher Shark',
    image: '/fish/deep/deep-10.png',
    speed: 4,
    size: 'large',
    rarity: 'epic',
    hp: 9,
    requiredAttacks: 9,
    rewards: {
      fish: 45,
      shells: 20,
      coins: 65,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_011',
    name: 'Fangtooth',
    image: '/fish/deep/deep-11.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 2,
    requiredAttacks: 2,
    rewards: {
      fish: 10,
      shells: 4,
      coins: 8,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_012',
    name: 'Frilled Shark',
    image: '/fish/deep/deep-12.png',
    speed: 3,
    size: 'medium',
    rarity: 'rare',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 12,
      coins: 40,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_013',
    name: 'Lasiognathus',
    image: '/fish/deep/deep-13.png',
    speed: 1,
    size: 'small',
    rarity: 'epic',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 25,
      shells: 10,
      coins: 28,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_014',
    name: 'Cookiecutter Shark',
    image: '/fish/deep/deep-14.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 22,
      shells: 8,
      coins: 28,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_015',
    name: 'Ocean Sunfish',
    image: '/fish/deep/deep-15.png',
    speed: 4,
    size: 'large',
    rarity: 'epic',
    hp: 10,
    requiredAttacks: 10,
    rewards: {
      fish: 50,
      shells: 25,
      coins: 80,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_016',
    name: 'Giant Isopod',
    image: '/fish/deep/deep-16.png',
    speed: 2,
    size: 'small',
    rarity: 'common',
    hp: 3,
    requiredAttacks: 3,
    rewards: {
      fish: 18,
      shells: 5,
      coins: 10,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_017',
    name: 'Barreleye Fish',
    image: '/fish/deep/deep-17.png',
    speed: 2,
    size: 'medium',
    rarity: 'rare',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 25,
      shells: 10,
      coins: 30,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_018',
    name: 'Viperfish',
    image: '/fish/deep/deep-18.png',
    speed: 2,
    size: 'small',
    rarity: 'epic',
    hp: 6,
    requiredAttacks: 6,
    rewards: {
      fish: 30,
      shells: 12,
      coins: 40,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_019',
    name: 'Snailfish',
    image: '/fish/deep/deep-19.png',
    speed: 3,
    size: 'medium',
    rarity: 'common',
    hp: 5,
    requiredAttacks: 5,
    rewards: {
      fish: 20,
      shells: 8,
      coins: 15,
    },
    habitat: 'deep ocean',
  },
  {
    id: 'deep_ocean_020',
    name: 'Barred Knifejaw',
    image: '/fish/deep/deep-20.png',
    speed: 3,
    size: 'small',
    rarity: 'rare',
    hp: 4,
    requiredAttacks: 4,
    rewards: {
      fish: 22,
      shells: 10,
      coins: 30,
    },
    habitat: 'deep ocean',
  },
];
